abook_homepage:
    pattern:  /home
    defaults: { _controller: AbookBundle:Default:index }
    
abook_list_contact:
    pattern:  /listcont
    defaults: { _controller: AbookBundle:Default:list }

abook_update_contact:
    pattern:  /updcont
    defaults: { _controller: AbookBundle:Default:update }
    
abook_add_contact:
    pattern:  /addcont
    defaults: { _controller: AbookBundle:Default:add }
