AB\AbookBundle\Entity\Categories:
    type: entity
    table: categories
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: true
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
