AB\AbookBundle\Entity\Contacts:
    type: entity
    table: Contacts
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        firstName:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: first_name
        lastName:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: last_name
        address:
            type: string
            length: 80
            fixed: false
            nullable: true
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    manyToOne:
        category:
            targetEntity: Categories
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
