AB\AbookBundle\Entity\ContactsEmails:
    type: entity
    table: contacts_emails
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        email:
            type: string
            length: 80
            fixed: false
            nullable: true
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    manyToOne:
        contact:
            targetEntity: Contacts
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
