AB\AbookBundle\Entity\Contacts:
    type: entity
    table: contacts
    fields:
        idContact:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_contact
            generator:
                strategy: IDENTITY
        firstName:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: first_name
        lastName:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: last_name
        address:
            type: string
            length: 80
            fixed: false
            nullable: true
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
