AB\AbookBundle\Entity\ContactsPhones:
    type: entity
    table: contacts_phones
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        phoneNumber:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: phone_number
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    manyToOne:
        contact:
            targetEntity: Contacts
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                contact_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
