AB\AbookBundle\Entity\Phones:
    type: entity
    table: phones
    fields:
        idPhone:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_phone
            generator:
                strategy: IDENTITY
        contactId:
            type: integer
            unsigned: false
            nullable: true
            column: contact_id
        phoneNumber:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: phone_number
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
