Groups:
    type: entity
    table: groups
    fields:
        idGroup:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_group
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 45
            fixed: false
            nullable: true
        active:
            type: boolean
            nullable: true
        deleted:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
